FROM jboss/wildfly:10.1.0.Final
MAINTAINER George Gastaldi<ggastald@redhat.com>

# Set the CATAPULT_VERSION env variable
ENV CATAPULT_VERSION 1.0.0-SNAPSHOT

ADD https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=snapshots&g=org.kontinuity.catapult&a=catapult-web&v=$CATAPULT_VERSION&e=war /opt/jboss/wildfly/standalone/deployments/catapult.war

USER root

RUN chown -R jboss:0 /opt/jboss/wildfly/standalone/deployments/ && chmod -R g+rw /opt/jboss/wildfly/standalone/deployments/

USER jboss